### ISSUE TITLE
小米手机运行CameraSample就崩溃

### ISSUE THREAD

**Issue by fandazeng** [hejunlin2013/MultiMediaSample#1]
01-06 15:47:48.570 8509-8509/com.hejunlin.camerasample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.hejunlin.camerasample, PID: 8509
                                                                         java.lang.RuntimeException: setParameters failed
                                                                             at android.hardware.Camera.native_setParameters(Native Method)
                                                                             at android.hardware.Camera.setParameters(Camera.java:2026)
                                                                             at com.hejunlin.camerasample.SurfacePreview.initCamera(SurfacePreview.java:74)
                                                                             at com.hejunlin.camerasample.SurfacePreview.access$000(SurfacePreview.java:17)
                                                                             at com.hejunlin.camerasample.SurfacePreview$1.onAutoFocus(SurfacePreview.java:57)
                                                                             at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1185)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:135)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5298)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:708)

**Comment by Hellozhongxin** [comment]
一加三 遇到同样问题

**Comment by Hellozhongxin** [comment]
查了一些资料，设置适配的预览尺寸和图片尺寸，应该就可以解决这个问题。
